# Generated by Django 4.2.6 on 2023-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emailconfirmationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'admin'), ('super_admin', 'Super Admin')], default='customer', max_length=50),
        ),
    ]
