# Generated by Django 4.2.6 on 2023-11-20 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_time",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="VendorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pancard", models.FileField(upload_to="media/vendor/pancard")),
                ("gst", models.FileField(upload_to="media/vendor/gst")),
                (
                    "proof_of_registration",
                    models.FileField(upload_to="media/vendor/proof_of_registration"),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
