# Generated by Django 4.2.6 on 2023-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_user_first_time_vendormodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.FileField(
                blank=True, null=True, upload_to="media/user/profile_photo"
            ),
        ),
    ]
