# Generated by Django 4.2.6 on 2023-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormodel",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendormodel",
            name="date_of_incorporation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendormodel",
            name="website",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="customer",
                max_length=50,
            ),
        ),
    ]
