# Generated by Django 4.2.6 on 2023-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hashtags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_unit",
            field=models.CharField(
                choices=[("piece", "Piece"), ("unit", "Unit"), ("default", "Default")],
                default="default",
                max_length=40,
            ),
        ),
    ]
