# Generated by Django 4.2.6 on 2023-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_hashtags_alter_product_price_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
